FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
ARG FRAMEWORK=net9.0
WORKDIR /src
COPY ["FormBE/FormBE.csproj", "FormBE/"]
COPY ["FormBE.Core/FormBE.Core.csproj", "FormBE.Core/"]
COPY ["FormBE.Persistence/FormBE.Persistence.csproj", "FormBE.Persistence/"]
COPY ["FormBE.Shared/FormBE.Shared.csproj", "FormBE.Shared/"]

ENV PATH=$PATH:/root/.dotnet/tools
RUN dotnet restore "FormBE/FormBE.csproj" -p:TargetFramework=$FRAMEWORK
RUN dotnet tool install --global dotnet-ef

COPY . .

RUN dotnet ef migrations bundle --project FormBE.Persistence/FormBE.Persistence.csproj --startup-project FormBE/FormBE.csproj --configuration $BUILD_CONFIGURATION --self-contained -r linux-musl-x64 --output /app/migration-bundle

FROM alpine:latest AS final
RUN apk add --no-cache gcompat libstdc++ icu-libs
WORKDIR /app
COPY --from=build /app/migration-bundle ./
ENTRYPOINT ["./migration-bundle"]