<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\FormBE.Persistence\FormBE.Persistence.csproj"/>
        <InternalsVisibleTo Include="FormBE.Test"/>
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="OneOf" Version="3.0.271"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Logic\" />
    </ItemGroup>

</Project>
