// <auto-generated />
using FormBE.Persistence.Util;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormBE.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250914161620_Fix typo")]
    partial class Fixtypo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("FormBE")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormBE.Persistence.Model.Field", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("FieldTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("field_type_id");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_optional");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_field");

                    b.HasIndex("FieldTypeId")
                        .HasDatabaseName("ix_field_field_type_id");

                    b.ToTable("field", "FormBE");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.FieldGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_field_group");

                    b.ToTable("field_group", "FormBE");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.FieldGroupField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FieldGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("field_group_id");

                    b.Property<long>("FieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("field_id");

                    b.HasKey("Id")
                        .HasName("pk_field_group_field");

                    b.HasIndex("FieldGroupId")
                        .HasDatabaseName("ix_field_group_field_field_group_id");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("ix_field_group_field_field_id");

                    b.ToTable("field_group_field", "FormBE");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.FieldGroupSingleChoiceField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FieldGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("field_group_id");

                    b.Property<long>("SingleChoiceFieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("single_choice_field_id");

                    b.HasKey("Id")
                        .HasName("pk_field_group_single_choice_field");

                    b.HasIndex("FieldGroupId")
                        .HasDatabaseName("ix_field_group_single_choice_field_field_group_id");

                    b.HasIndex("SingleChoiceFieldId")
                        .HasDatabaseName("ix_field_group_single_choice_field_single_choice_field_id");

                    b.ToTable("field_group_single_choice_field", "FormBE");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.FieldResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("field_id");

                    b.Property<Instant>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telephone_number");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_field_response");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("ix_field_response_field_id");

                    b.ToTable("field_response", "FormBE");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.FieldType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Regex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("regex");

                    b.HasKey("Id")
                        .HasName("pk_field_type");

                    b.ToTable("field_type", "FormBE");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.Form", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_form");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_form_group_id");

                    b.ToTable("form", "FormBE");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.FormFieldGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FieldGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("field_group_id");

                    b.Property<long>("FormId")
                        .HasColumnType("bigint")
                        .HasColumnName("form_id");

                    b.HasKey("Id")
                        .HasName("pk_form_field_group");

                    b.HasIndex("FieldGroupId")
                        .HasDatabaseName("ix_form_field_group_field_group_id");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_form_field_group_form_id");

                    b.ToTable("form_field_group", "FormBE");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_group");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_group_parent_id");

                    b.ToTable("group", "FormBE");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.Option", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("SingleChoiceFieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("single_choice_field_id");

                    b.HasKey("Id")
                        .HasName("pk_option");

                    b.HasIndex("SingleChoiceFieldId")
                        .HasDatabaseName("ix_option_single_choice_field_id");

                    b.ToTable("option", "FormBE");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.OptionField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("field_id");

                    b.Property<long>("OptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("option_id");

                    b.HasKey("Id")
                        .HasName("pk_option_field");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("ix_option_field_field_id");

                    b.HasIndex("OptionId")
                        .HasDatabaseName("ix_option_field_option_id");

                    b.ToTable("option_field", "FormBE");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.OptionResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("option_id");

                    b.Property<Instant>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telephone_number");

                    b.HasKey("Id")
                        .HasName("pk_option_response");

                    b.HasIndex("OptionId")
                        .HasDatabaseName("ix_option_response_option_id");

                    b.ToTable("option_response", "FormBE");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.SingleChoiceField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_single_choice_field");

                    b.ToTable("single_choice_field", "FormBE");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.Field", b =>
                {
                    b.HasOne("FormBE.Persistence.Model.FieldType", "FieldType")
                        .WithMany("Fields")
                        .HasForeignKey("FieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_field_field_type_field_type_id");

                    b.Navigation("FieldType");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.FieldGroupField", b =>
                {
                    b.HasOne("FormBE.Persistence.Model.FieldGroup", "FieldGroup")
                        .WithMany("FieldGroupFields")
                        .HasForeignKey("FieldGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_field_group_field_field_group_field_group_id");

                    b.HasOne("FormBE.Persistence.Model.Field", "Field")
                        .WithMany("FieldGroupFields")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_field_group_field_field_field_id");

                    b.Navigation("Field");

                    b.Navigation("FieldGroup");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.FieldGroupSingleChoiceField", b =>
                {
                    b.HasOne("FormBE.Persistence.Model.FieldGroup", "FieldGroup")
                        .WithMany("FieldGroupSingleChoiceFields")
                        .HasForeignKey("FieldGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_field_group_single_choice_field_field_group_field_group_id");

                    b.HasOne("FormBE.Persistence.Model.SingleChoiceField", "SingleChoiceField")
                        .WithMany("FieldGroupSingleChoiceFields")
                        .HasForeignKey("SingleChoiceFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_field_group_single_choice_field_single_choice_field_single_");

                    b.Navigation("FieldGroup");

                    b.Navigation("SingleChoiceField");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.FieldResponse", b =>
                {
                    b.HasOne("FormBE.Persistence.Model.Field", "Field")
                        .WithMany("FieldResponses")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_field_response_field_field_id");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.Form", b =>
                {
                    b.HasOne("FormBE.Persistence.Model.Group", "Group")
                        .WithMany("Forms")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_form_group_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.FormFieldGroup", b =>
                {
                    b.HasOne("FormBE.Persistence.Model.FieldGroup", "FieldGroup")
                        .WithMany("FormFieldGroups")
                        .HasForeignKey("FieldGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_field_group_field_group_field_group_id");

                    b.HasOne("FormBE.Persistence.Model.Form", "Form")
                        .WithMany("FormFieldGroups")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_field_group_form_form_id");

                    b.Navigation("FieldGroup");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.Group", b =>
                {
                    b.HasOne("FormBE.Persistence.Model.Group", "Parent")
                        .WithMany("SubGroups")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_group_group_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.Option", b =>
                {
                    b.HasOne("FormBE.Persistence.Model.SingleChoiceField", "SingleChoiceField")
                        .WithMany("Options")
                        .HasForeignKey("SingleChoiceFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_option_single_choice_field_single_choice_field_id");

                    b.Navigation("SingleChoiceField");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.OptionField", b =>
                {
                    b.HasOne("FormBE.Persistence.Model.Field", "Field")
                        .WithMany("OptionFields")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_option_field_field_field_id");

                    b.HasOne("FormBE.Persistence.Model.Option", "Option")
                        .WithMany("OptionFields")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_option_field_option_option_id");

                    b.Navigation("Field");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.OptionResponse", b =>
                {
                    b.HasOne("FormBE.Persistence.Model.Option", "Option")
                        .WithMany("OptionResponses")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_option_response_option_option_id");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.Field", b =>
                {
                    b.Navigation("FieldGroupFields");

                    b.Navigation("FieldResponses");

                    b.Navigation("OptionFields");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.FieldGroup", b =>
                {
                    b.Navigation("FieldGroupFields");

                    b.Navigation("FieldGroupSingleChoiceFields");

                    b.Navigation("FormFieldGroups");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.FieldType", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.Form", b =>
                {
                    b.Navigation("FormFieldGroups");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.Group", b =>
                {
                    b.Navigation("Forms");

                    b.Navigation("SubGroups");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.Option", b =>
                {
                    b.Navigation("OptionFields");

                    b.Navigation("OptionResponses");
                });

            modelBuilder.Entity("FormBE.Persistence.Model.SingleChoiceField", b =>
                {
                    b.Navigation("FieldGroupSingleChoiceFields");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
